// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMh2_pfZdsijnykAdMNdeKjLSbiUeySXw',
    appId: '1:423633173623:web:54020cb0083cb4c3fa5a72',
    messagingSenderId: '423633173623',
    projectId: 'notesmanagement-007',
    authDomain: 'notesmanagement-007.firebaseapp.com',
    storageBucket: 'notesmanagement-007.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5JAQnczF41g3agTuQ8x06tInnyCv_gKs',
    appId: '1:423633173623:android:cd16d7267dc75f39fa5a72',
    messagingSenderId: '423633173623',
    projectId: 'notesmanagement-007',
    storageBucket: 'notesmanagement-007.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0O0W1BPDx_XB0h3pv2kiy7YgdFWOvPSQ',
    appId: '1:423633173623:ios:d3e1d71aa75db5dbfa5a72',
    messagingSenderId: '423633173623',
    projectId: 'notesmanagement-007',
    storageBucket: 'notesmanagement-007.firebasestorage.app',
    iosBundleId: 'com.example.noteSystem',
  );
}
